language: java
jdk:
  - openjdk7
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
before_script:
  - npm install protractor
  - ./node_modules/protractor/bin/webdriver-manager update --standalone
  - mvn exec:java &
  - sleep 3
script:
  - ./node_modules/protractor/bin/protractor src/test/js/textManager.conf.js
